title: Australian Poetry
email: info@australianpoetry.com
description: "Celebrating the poets, poems and poetic heritage of Australia."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://australianpoetry.com"
theme: minima
collections:
  poets:
    output: true
  poems:
    output: true
  articles:
    output: true
plugins: [jekyll-feed]
markdown: kramdown
permalink: /:collection/:name/
